output:
  formats: line-number

linters:
  enable:
    - goimports
    - gofmt
    - misspell
    - errorlint
    - revive

linters-settings:
  errcheck:
    exclude-functions:
      - (github.com/go-kit/kit/log.Logger).Log
      - (github.com/go-kit/log.Logger).Log

  errorlint:
    # Check for plain error comparisons.
    comparison: true

    # Do not check for plain type assertions and type switches.
    asserts: false

    errorf: false

run:
  timeout: 5m

issues:
  exclude-dirs:
    - alerting/channels # TODO(gotjosh): remove this once we get to aligning the notifiers.

  # List of build tags, all linters use it.
  build-tags:
    - netgo
    - requires_docker
    - requires_libpcap
