output:
  format: line-number

linters:
  enable:
    - goimports
    - gofmt
    - misspell
    - errorlint
    - revive

linters-settings:
  errcheck:
    # path to a file containing a list of functions to exclude from checking
    # see https://github.com/kisielk/errcheck#excluding-functions for details
    exclude: ./.errcheck-exclude

  errorlint:
    # Check for plain error comparisons.
    comparison: true

    # Do not check for plain type assertions and type switches.
    asserts: false

    errorf: false

run:
  timeout: 5m

  skip-dirs:
    - alerting/channels # TODO(gotjosh): remove this once we get to aligning the notifiers.

  # List of build tags, all linters use it.
  build-tags:
    - netgo
    - requires_docker
    - requires_libpcap
