package wecom

import (
	"github.com/grafana/alerting/receivers/schema"
	v1 "github.com/grafana/alerting/receivers/wecom/v1"
)

const Type schema.IntegrationType = "wecom"

var Schema = schema.NewIntegrationTypeSchema(
	Type,
	v1.Version, // currentVersion
	"WeCom",
	"WeCom settings",
	"Send alerts generated by Grafana to WeCom",
	"", // info
	false, // deprecated
	v1.Schema,
)
