---
{
   "kind": "pipeline",
   "name": "validate-pull-request",
   "steps": [
      {
         "commands": [
            "make mod-check"
         ],
         "image": "golang:1.21.6",
         "name": "make-mod-check"
      },
      {
         "commands": [
            "make lint"
         ],
         "image": "golang:1.21.6",
         "name": "make-lint"
      },
      {
         "commands": [
            "make test"
         ],
         "image": "golang:1.21.6",
         "name": "make-test"
      }
   ]
}
---
kind: signature
hmac: 29948fb9c32942894cb6995d0660e4003124e7f0cec5f71f0da7fd51a3749404

...
