---
{
   "kind": "pipeline",
   "name": "validate-pull-request",
   "steps": [
      {
         "commands": [
            "make mod-check"
         ],
         "image": "golang:1.23.1",
         "name": "make-mod-check"
      },
      {
         "commands": [
            "make lint"
         ],
         "image": "golang:1.23.1",
         "name": "make-lint"
      },
      {
         "commands": [
            "make test"
         ],
         "image": "golang:1.23.1",
         "name": "make-test"
      }
   ]
}
---
kind: signature
hmac: a1c47c1835e2c4bf1c1d588faee8eeee55f4346113dca9220db799f6f3efa629

...
